### ISSUE TITLE
Does it need to ship its own autoprefixer?

### ISSUE THREAD

**Issue by mudrd8mz** [roelmann/moodle-theme_waxed#6]
Is there a need for its own classes/autoprefixer.php? Could not it simply use the once already coming with the Boost theme? If not, then changes / customizations / differences would be good to have documented and explained.

By the way, the original autoprefixer states clearly that

> This autoprefixer has been developed to satisfy the basic needs of the
> theme Boost when working with Bootstrap 4 alpha. We do not recommend
> that this tool is shared, nor used outside of this theme.

**Comment by roelmann** [comment]
There are no current customizations to the autoprefixer, it is currently using the one that was in Boost when Waxed was created. However, even if there are currently no changes, that warning above is sufficient to make me think that it should be in Waxed so that customizations and developments specific to Waxed *can* be included when necessary.
